name: gaussian_splatting
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.11.11
  - nvidia/label/cuda-12.4.0::cuda-toolkit
  - plyfile=1.1
  - pip=24.3.1
  - pytorch=2.5.0
  - torchaudio=2.5.0
  - torchvision=0.20.0
  - tqdm
  - pip:
    - numpy==1.26
    - opencv-python==4.8.1.78
    - munch
    - trimesh
    - matplotlib==3.10.0
    - evo==1.30.6
    - open3d==0.17.0
    - torchmetrics
    - imgviz
    - PyOpenGL
    - glfw
    - PyGLM
    - wandb
    - lpips
    - rich
    - ruff
    - PyQt5
